### ISSUE TITLE
Populating the search results takes too much time

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/PoEHandBook#1]
If the query returns too many search results, the input hogs for a few seconds while populating the WrapPanel with Controls.SearchResult objects.

Performing the search query itself uses up only 0.30% of CPU time, the main bottle necks are here (from MainPage.xaml.cs)
```c#
foreach (var sr in _lastResults)
{
    var result = new Controls.SearchResult(sr, queries, NavigationService);
    PnlResults.Children.Add(result);
}
```

The first line in the loop body creates a search result control and the second adds it to the wrap panel.
Need to find a way to speed this up, either by culling invisible search results when browsing the panel via scroll viewer or by gradually adding controls in background, or maybe in a different way.

I'm not a WPF expert so I'm not sure what are the best practices when doing this.

**Comment by EmmittJ** [comment]
This action should be threaded. You don't want control of the app lost because you are populating a search. 

Making this threaded means that a user can type what ever they want and you can continue to update their search results without any freezing or input lag.

**Comment by Tyrrrz** [comment]
@EmmittJ yes, i realize that, but a WrapPanel can only be updated from a thread it was created in, right? Trying to populate its children from a different thread throws "The calling thread cannot access this object because a different thread owns it" exception

**Comment by EmmittJ** [comment]
Try using async functions. It is early, and I was thinking of the wrong
thing. In the skilltree planner we use async almost everywhere and we don't
have problems with input freezing.

**Comment by EmmittJ** [comment]
As a side note for threads, you should be able to delegate elements to them
that they can modify. It has been a long time since I worked with threads
though.

**Comment by Tyrrrz** [comment]
@EmmittJ Turns out, the way it should be done in WPF (i'm still new to it a bit) is via Dispatchers. So with that being said, the issue is no longer relevant.
